/-
Copyright (c) 2026 CatCrypt Contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: CatCrypt Contributors
-/
import VersoManual

open Verso.Genre Manual

#doc (Manual) "CatCrypt Core — machine-checked foundations for cryptographic proofs" =>

🚧 *Under construction.* CatCrypt has been developed over many months with the
help of AI. It serves as the basis for a large library of cryptographic protocols
([ePrint 2026/604](https://eprint.iacr.org/2026/604.pdf)); the full project also
includes a categorical foundation for cryptography, a certified compiler for
cryptography, and a partially verified version of Hax. Many methods have been used
to ensure correctness and completeness, but a full manual audit is ongoing. The
project aims to connect to other Lean projects — for example those supported by
[Verified zkEVM](https://verified-zkevm.org/), which has also partially supported
CatCrypt.

The core of CatCrypt: a self-contained Lean 4 + Mathlib basis for game-based
cryptographic security proofs. It provides sub-distributions, a
stateful-probabilistic program monad, a probabilistic relational Hoare logic,
state-separated packages, and proof automation — the substrate on which concrete
protocol proofs are built.

This is the minimal-basis release. The universal-composability theory, the
quantum verification layer, the verified compilation pipeline, and the catalogue
of concrete protocols live in separate, larger distributions that build on this
one.

The code blocks below are illustrative transcriptions. For the full
per-declaration API — every declaration with its signature and a link to source —
see the [API reference](api/index.html), generated by doc-gen4 and served
alongside this manual.

# How this documentation is organized

Three layers document the library, each with a distinct job; read them together.

- _This manual_ (Verso) is the *narrative*. It explains how the layers fit and the
  relation to SSProve; it does not list every declaration or every worked example.
- The [blueprint](../blueprint/) is the *statement graph*: one chapter per layer
  and per worked example, each formal statement shown with its dependencies as a
  browsable graph and linked to its API entry. Go here to see _what is proved and
  how the results depend on each other_ — including the eighteen worked examples
  (one-time pad, PRF, Schnorr, ElGamal, and the rest) that this manual does not
  walk through individually.
- The [API reference](../api/) is the *generated, per-declaration reference* —
  every definition, theorem, and instance, searchable. It is the ground truth:
  generated from source, so it cannot drift.

A rule of thumb: the blueprint carries the informal statement and the dependency
picture; for the full formal definition, follow its link into the API reference.
The worked-example sources live in `CatCryptCore/Examples/`.

# The program monad

Everything rests on `SPComp`, the stateful-probabilistic computation monad: a
computation reads and writes a typed `Heap` and returns a sub-distribution over
its result paired with the final heap.

```
-- Core/Code.lean
def SPComp (α : Type) : Type := Heap → SDistr (α × Heap)
```

`SDistr` (in `Prob/`) is the type of sub-distributions — probability mass that
may sum to less than one, so partial and failing computations are first-class.
The monad has `pure`, `bind`, `sample` (draw from a distribution), and `get`/`set`
(typed heap access), with the monad laws proved as rewrite lemmas
(`pure_bind`, `bind_pure`, `bind_assoc`).

A syntactic companion, `SPTree` (`Core/SPTree.lean`), preserves the structure of a
computation as a free-monad-like tree, so cost can be read off by structural
recursion where the denotational `SPComp` view has already collapsed it.

# Games, advantage, and assumptions

A security game is an `SPComp` program; an adversary's ability to tell two games
apart is its advantage.

```
-- Crypto/Advantage.lean
-- AdvantageA G₀ G₁ A : the distinguishing advantage of adversary A between
-- games G₀ and G₁, valued in ℝ≥0∞.
```

The standard hardness assumptions are stated once, in `Crypto/Assumptions/`, as
advantage bounds an adversary cannot beat: DDH, CDH, Gap-DH, discrete log,
`t`-SDH / `q`-SDH, co-CDH, ODH, collision resistance, one-way functions, PRP,
RSA, AEAD, and MAC unforgeability. `Crypto/Assumptions/Catalog.lean` indexes them
with their literature references. Security theorems are reductions: they take one
of these as a hypothesis and conclude a protocol bound.

# The relational logic

Game hops are justified in a probabilistic relational Hoare logic (pRHL) over
pairs of `SPComp` programs, with a precondition relating the two initial heaps
and a postcondition relating the two results.

```
-- Relational/Judgment.lean
-- rHoare Φ c₁ c₂ Ψ : under precondition Φ, the programs c₁ and c₂ satisfy
-- the relational postcondition Ψ.
```

The rules in `Relational/` cover synchronization, framing, reordering, and
remembered-value bookkeeping (`Tactics/Remember.lean`). The `Tactics/` layer
drives them: `ssprove_sync`, invariant restoration, weakest-precondition and
strongest-postcondition stepping, lazy sampling, up-to-bad reasoning, and the
`ssprove_crypto` pipeline that sequences them.

# Packages and the categorical structure

`Package/` is an interface-based package algebra: computations are grouped behind
typed import/export interfaces and composed by linking. `Category/` gives the
semantic backbone — the Kleisli category of `SPComp`, a family bicategory, and
the cocartesian / affine structure that package composition realizes.

`Deep/` is a deep embedding: a syntactic package calculus with a semantic
evaluation into `SPComp` (`RawCode` reflection), and `Bridge/` connects the deep
and shallow views so a syntactic manipulation transfers to the denotational
semantics.

# Relation to SSProve

The program logic, package algebra, and the `ssprove_*` tactic family were
*initiated from* the design of SSProve, the Rocq framework for modular
cryptographic proofs, and have since *diverged* (see below):

> P. G. Haselwarter, E. Rivas, A. Van Muylder, T. Winterhalter, C. Abate,
> N. Sidorenco, C. Hriţcu, K. Maillard, B. Spitters.
> *SSProve: A Foundational Framework for Modular Cryptographic Proofs in Coq.*
> ACM Transactions on Programming Languages and Systems 45(3), 2023.

*SSProve → CatCrypt.* A dictionary for readers who know SSProve:

- `raw_code A` → `SPComp α` (shallow) or `RawCode` (deep).
- `sampler` / `#put` / `#get` / `ret` → `SPComp.sample` / `.set` / `.get` / `.pure`.
- `raw_package` / `link` / `par` → `RawPackage` (or `DeepPackage`) / `.link` / `.par`.
- `Advantage` and its triangle inequality → `Advantage`, `advantage_triangle`.
- the reduction lemma → `DeepNomAdvantage_link`.
- perfect indistinguishability (`≈₀`) → zero `Advantage` (`Advantage G₀ G₁ = 0`, e.g. `otp_perfect_indcpa`).
- `⊨ ⦃pre⦄ c₁ ~ c₂ ⦃post⦄` → `⊨ ⦃Φ⦄ c₁ ~ c₂ ⦃Ψ⦄` (`rHoare`).
- `ssprove_sync`, `ssprove_swap`, `ssprove_code_simpl`, `ssprove_valid` → the same names.

*Tactic families.* The `ssprove_*` suite in `Tactics/` mirrors the SSProve and
EasyCrypt proof verbs:

- _sync stepping_ — `ssprove_sync`, `ssprove_sync_bij`, `ssprove_bind`, `ssprove_conseq`;
- _bisimulation_ — `ssprove_sim`, `ssprove_sim_auto`, `ssprove_try_bij`, `ssprove_try_bij₂`;
- _EasyCrypt verbs_ — `ssprove_proc`, `ssprove_wp`, `ssprove_sp`, `ssprove_rnd_lhs`/`_rhs`, `ssprove_rcondt`/`_rcondf`, `ssprove_call`;
- _invariants and memory_ — `ssprove_invariant`, `ssprove_restore`, `ssprove_remember_lhs`/`_rhs`, `ssprove_forget`;
- _ProofFrog simplification_ (verified) — `ssprove_dead_code`, `ssprove_copy_propagate`, `ssprove_contract_all`, `ssprove_canonicalize`, `ssprove_auto_pf`;
- _advantage chaining_ — `ssprove_triangle`, with the top-level driver `ssprove_crypto`.

*Where CatCrypt diverged.* It started from SSProve's design; the Lean and Mathlib
substrate then reshaped it:

- _foundational probability from Mathlib_ — `SDistr = PMF (Option α)`, so advantage and every bound reduce to Mathlib measure theory, with no separate probability development to trust;
- _a shallow monad where automation applies_ — `SPComp` is an ordinary Lean monad, so `simp`, `grind`, and `bind_align` work directly; CatCrypt works primarily on the shallow embedding, but uses the deep-embedding `RawCode` for reflective tactics;
- _EasyCrypt's proof-mode ergonomics on SSProve's semantics_ — the `ssprove_*` verbs give EasyCrypt's tactic breadth on foundational pRHL;
- _ProofFrog passes are theorems_, not an unverified preprocessor ([ProofFrog](https://prooffrog.github.io/));
- _proofs are often shorter than EasyCrypt's_ — combining formalization convenience with a foundational tool.

# Tactic provenance

The `ssprove_*` prefix names the suite, not the origin of each tactic. Four sources
contribute, and each tactic's own docstring names the source it came from:

- _SSProve_ keeps its own names — the synchronization, swap, memory, invariant, and
  advantage verbs: `ssprove_sync`, `ssprove_swap`, `ssprove_bind`, `ssprove_conseq`,
  `ssprove_contract_get`/`_put`, `ssprove_remember`/`_forget`/`_remind`,
  `ssprove_restore`, `ssprove_invariant`, `ssprove_eager`/`_lazy_unfold`,
  `ssprove_triangle`, `ssprove_valid`, `ssprove_code_simpl`.
- _EasyCrypt_ proof-mode verbs, mirrored on foundational pRHL: `ssprove_proc`,
  `ssprove_wp`, `ssprove_sp`, `ssprove_call`, `ssprove_rcondt`/`_rcondf`,
  `ssprove_rnd`/`_rnd_lhs`/`_rnd_rhs`, `ssprove_sim`, `ssprove_auto_ec`,
  `ssprove_inline_lhs`/`_rhs`.
- _ProofFrog_ game-simplification passes, here proved as theorems:
  `ssprove_dead_code`, `ssprove_copy_propagate`, `ssprove_unreachable`,
  `ssprove_canonicalize`, `ssprove_contract_all`, `ssprove_auto_pf`.
- _CatCrypt_ original to this library: `ssprove_crypto`,
  `ssprove_try_bij`/`_try_bij₂`, `ssprove_rspec`, `ssprove_reorder`, `bind_align`,
  `bind_vcgen`, and the deep/shallow bridge tactics.

The `_ec` and `_pf` suffixes mark the two automation drivers by source, keeping the
EasyCrypt `ssprove_auto_ec` distinct from the ProofFrog `ssprove_auto_pf`.

# Other projects

EasyCrypt is an important inspiration for both SSProve and CatCrypt. VCVio builds
on the design of FCF, the Foundational Cryptography Framework, which was itself
inspired by EasyCrypt. That functional style seems to work as well as EasyCrypt's
imperative language for some classes of protocols, such as zero-knowledge, but it
lacks dedicated support for communication protocols like TLS, for which
state-separating proofs were invented. Interoperability with VCVio and ArkLib is
provided by the separate `catcrypt-vcvio` and `catcrypt-arklib` packages, built on
top of this basis rather than inside it.

# What's included

- a probability layer: sub-distributions, couplings, the birthday bound, Schwartz–Zippel;
- the `SPComp` program monad over a typed heap;
- the probabilistic relational Hoare logic and the `ssprove_*` tactic suite;
- the package algebra and its categorical structure, with a deep syntactic embedding;
- the crypto foundations: games, advantage, hybrid arguments, and the standard assumptions;
- the Pointcheval–Stern and Bellare–Neven forking lemmas;
- Montgomery-curve arithmetic for X25519;
- eighteen worked examples from Rosulek's _Joy of Cryptography_ (`CatCryptCore/Examples/`) — one-time pad, PRF, PRG, Schnorr, ElGamal, and more — each with a chapter in the [blueprint](../blueprint/).

The full per-module map, with every declaration, is the
[API reference](api/index.html).
